#!/bin/sh /etc/rc.common
# ZeroTier OpenWrt Init Script

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/zerotier-one -d
    procd_set_param respawn  # 崩溃后自动重启
    procd_close_instance
}

stop_service() {
    killall zerotier-one
}

service_triggers() {
    procd_add_reload_trigger "zerotier"
}
